# Generated by Django 6.0.6 on 2026-07-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("issue_date", models.CharField(blank=True, max_length=100)),
                ("credential_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="certificates/")),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("details", models.CharField(blank=True, max_length=200)),
                ("start_date", models.CharField(blank=True, max_length=100)),
                ("end_date", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.CharField(max_length=100)),
                ("end_date", models.CharField(default="PRESENT", max_length=100)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("resume", models.FileField(blank=True, upload_to="resumes/")),
                ("avatar", models.ImageField(blank=True, upload_to="profile/")),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("percentage", models.IntegerField(default=0)),
                (
                    "skill_type",
                    models.CharField(
                        choices=[("CORE", "Core Competency"), ("TECH", "Tech Skill")],
                        default="CORE",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
